export EDITOR=hx

alias rebuild="sudo nixos-rebuild switch -I nixos-config=$HOME/nixos/configuration.nix";
alias config="$EDITOR $HOME/nixos";
alias ls="ls -l";
alias ta="tmux attach-session -t";
alias tn="tmux new-session -s";
alias tl="tmux ls";

eval "$(direnv hook bash)"

export GIT_PS1_SHOWDIRTYSTATE=1
source ~/.nix-profile/share/git/contrib/completion/git-prompt.sh
export PS1='[\u@\h:\W$(__git_ps1 " (%s)")]\$ '

export HISTCONTROL=ignoreboth:erasedups
