export EDITOR=hx

alias git="git-fzf";
alias rebuild="sudo nixos-rebuild switch -I nixos-config=$HOME/nixos/configuration.nix";
alias config="$EDITOR $HOME/nixos";
alias gitn="git --no-pager";
alias ls="ls -l";
alias ta="tmux attach-session -t";
alias tn="tmux new-session -s";
alias tl="tmux ls";
alias nixde="echo use nix > .envrc; direnv allow";
alias nixdef="echo use flake > .envrc; direnv allow";
alias gclip="git log --oneline | fzf | cut -f1 -d' ' | xclip -rmlastnl -selection clipboard";
alias git-watch="watchexec --quiet --clear=reset --no-default-ignore --ignore='*.lock' -- git status --short --branch";

run-once () {
	if [ $# = 1 ]
	then
		exec nix-shell -p "$1" --run "exec $*"
	else
		>&2 echo 'usage: run-once <package> [args...]'
	fi
}
export -f run-once

eval "$(direnv hook bash)"

export GIT_PS1_SHOWDIRTYSTATE=1
source ~/.nix-profile/share/git/contrib/completion/git-prompt.sh
export PS1='[\u@\h:\w$(__git_ps1 " (%s)")]\$ '
